# Generated by Django 5.2.11 on 2026-03-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order_num', 'name']},
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='categories__slug_9b1a28_idx',
        ),
        migrations.RemoveIndex(
            model_name='category',
            name='categories__parent__91c7d9_idx',
        ),
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='category',
            name='icon',
            field=models.ImageField(blank=True, default=2, upload_to='categories/icons/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
